[tool.poetry]
name = "tools"
version = "0.1.0"
description = "Miscellaneous python tools"
authors = ["Kelvin <26215587+zktuong@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.2.4"
numpy = "^1.21.6"
matplotlib = "^3.5.2"
scanpy = "^1.7.1"
anndata = "^0.7.6"

[tool.poetry.dev-dependencies]
python = "^3.7"
pandas = "^1.2.4"
numpy = "^1.21.6"
matplotlib = "^3.5.2"
scanpy = "^1.7.1"
anndata = "^0.7.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
